// automatically generated by the FlatBuffers compiler, do not modify

package flatbuf

/// ----------------------------------------------------------------------
/// Endianness of the platform that produces the RecordBatch
const (
	EndiannessLittle = 0
	EndiannessBig = 1
)

var EnumNamesEndianness = map[int]string{
	EndiannessLittle:"Little",
	EndiannessBig:"Big",
}

