// automatically generated by the FlatBuffers compiler, do not modify

package flatbuf

const (
	IntervalUnitYEAR_MONTH = 0
	IntervalUnitDAY_TIME = 1
)

var EnumNamesIntervalUnit = map[int]string{
	IntervalUnitYEAR_MONTH:"YEAR_MONTH",
	IntervalUnitDAY_TIME:"DAY_TIME",
}

