// automatically generated by the FlatBuffers compiler, do not modify

package flatbuf

const (
	MetadataVersionV1_SNAPSHOT = 0
)

var EnumNamesMetadataVersion = map[int]string{
	MetadataVersionV1_SNAPSHOT:"V1_SNAPSHOT",
}

