// automatically generated by the FlatBuffers compiler, do not modify

package flatbuf

const (
	PrecisionHALF = 0
	PrecisionSINGLE = 1
	PrecisionDOUBLE = 2
)

var EnumNamesPrecision = map[int]string{
	PrecisionHALF:"HALF",
	PrecisionSINGLE:"SINGLE",
	PrecisionDOUBLE:"DOUBLE",
}

