// automatically generated by the FlatBuffers compiler, do not modify

package flatbuf

const (
	TimeUnitSECOND = 0
	TimeUnitMILLISECOND = 1
	TimeUnitMICROSECOND = 2
	TimeUnitNANOSECOND = 3
)

var EnumNamesTimeUnit = map[int]string{
	TimeUnitSECOND:"SECOND",
	TimeUnitMILLISECOND:"MILLISECOND",
	TimeUnitMICROSECOND:"MICROSECOND",
	TimeUnitNANOSECOND:"NANOSECOND",
}

