// automatically generated by the FlatBuffers compiler, do not modify

package flatbuf

const (
	UnionModeSparse = 0
	UnionModeDense = 1
)

var EnumNamesUnionMode = map[int]string{
	UnionModeSparse:"Sparse",
	UnionModeDense:"Dense",
}

