// automatically generated by the FlatBuffers compiler, do not modify

package flatbuf

/// ----------------------------------------------------------------------
/// The possible types of a vector
const (
	/// used in List type, Dense Union and variable length primitive types (String, Binary)
	VectorTypeOFFSET = 0
	/// actual data, either wixed width primitive types in slots or variable width delimited by an OFFSET vector
	VectorTypeDATA = 1
	/// Bit vector indicating if each value is null
	VectorTypeVALIDITY = 2
	/// Type vector used in Union type
	VectorTypeTYPE = 3
)

var EnumNamesVectorType = map[int]string{
	VectorTypeOFFSET:"OFFSET",
	VectorTypeDATA:"DATA",
	VectorTypeVALIDITY:"VALIDITY",
	VectorTypeTYPE:"TYPE",
}

